# ---------------------------------------------------------------------------
# LongueurTotal.py
# Created on: 2013-07-24 08:38:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
reseau_arc = "reseau arc"
Peyrissas = "H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas"
Classe_d’entités_en_sortie = "C:\\Users\\Villierme\\Documents\\ArcGIS\\Default.gdb\\arc_Clip"
Peyrissas_SpatialJoin = "C:\\Users\\Villierme\\Documents\\ArcGIS\\Default.gdb\\Peyrissas_SpatialJoin"

# Process: Découper
arcpy.Clip_analysis(reseau_arc, Peyrissas, Classe_d’entités_en_sortie, "")

# Process: Jointure spatiale
arcpy.SpatialJoin_analysis(Peyrissas, Classe_d’entités_en_sortie, Peyrissas_SpatialJoin, "JOIN_ONE_TO_ONE", "KEEP_ALL", "ID \"ID\" true true false 24 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,ID,-1,-1;PREC_PLANI \"PREC_PLANI\" true true false 4 Float 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,PREC_PLANI,-1,-1;NOM \"NOM\" true true false 45 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,NOM,-1,-1;CODE_INSEE \"CODE_INSEE\" true true false 5 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,CODE_INSEE,-1,-1;STATUT \"STATUT\" true true false 20 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,STATUT,-1,-1;CANTON \"CANTON\" true true false 45 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,CANTON,-1,-1;ARRONDISST \"ARRONDISST\" true true false 45 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,ARRONDISST,-1,-1;DEPART \"DEPART\" true true false 30 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,DEPART,-1,-1;REGION \"REGION\" true true false 30 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,REGION,-1,-1;POPUL \"POPUL\" true true false 4 Long 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,POPUL,-1,-1;MULTICAN \"MULTICAN\" true true false 3 Text 0 0 ,First,#,H:\\5_STAGE\\HedgeTools\\DataTest\\Data.gdb\\Peyrissas,MULTICAN,-1,-1;LongueurTotal \"LongueurTotal\" true true false 50 Double 0 0 ,Sum,#,C:\\Users\\Villierme\\Documents\\ArcGIS\\Default.gdb\\arc_Clip,Shape_length,-1,-1", "CONTAINS", "", "")

