# ---------------------------------------------------------------------------
# LongueurTotalDensite.py
# Created on: 2013-07-25 12:30:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os

from arcpy import env
env.overwriteOutput = True

# Local variables:
polystrate = arcpy.GetParameterAsText(0)
champStrate = arcpy.GetParameterAsText(1)
sitetude = arcpy.GetParameterAsText(2)
output = arcpy.GetParameterAsText(3)
gdb, nameOutput = os.path.split(output)
gdbSetude, namesitetude = os.path.split(sitetude)

# Process: Découper et identifier
Clipoly = os.path.join(gdb, "Clipoly")
arcpy.Clip_analysis(polystrate, sitetude, Clipoly, "")

# On utilise un curseur de recherche :
scur = arcpy.SearchCursor(Clipoly)

# On stock toute les valeurs dans une liste :
lStrate, dArea, TotalArea = [], dict(), 0
for row in scur:
    # il faut encoder les valeurs
    #Strate = (row.getValue(champStrate)).encode('utf8')
    Strate = row.getValue(champStrate)
    # les variables qui nous permettent de savoir si l'on a une autre valeur.
     # on applique des condittions pour créer ou pas une nouvelle entrée du dictionnaire
    if Strate not in dArea : dArea[Strate]={"liste"+ str(Strate) : [], "Area": row.Shape_Area}
    if Strate in dArea : dArea[Strate]["Area"] = dArea[Strate]["Area"] + row.Shape_Area
    TotalArea = TotalArea + row.Shape_Area
    lStrate.append(Strate)

del row, scur

# on fait une copie de la géométrie du site d'étude
arcpy.Copy_management(sitetude,output)
# on cherche les valeurs unique de la liste de valeur :
lValUnique = frozenset(lStrate)

# stocke dans une liste les valeurs unique et on créer les champs :
listValeur =[]
for val in lValUnique:
    val= val.encode('utf8')
    arcpy.AddField_management(output, champStrate + "_" +val, "TEXT")
    listValeur.append(val)



# on met à jour les champs:
ucur = arcpy.UpdateCursor(output)
for row in ucur :
    for Valeur in listValeur:
        pourcentage = (dArea[Valeur]["Area"]*1.0/TotalLength*1.0)*100.
        row.setValue(champStrate + "_" +Valeur, pourcentage)
        ucur.updateRow(row)
