# ---------------------------------------------------------------------------
# TrimLine.py
# Created on: 2013-11-20 13:57:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: TrimLine <Input_Skeleton> <Output_Line> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Script arguments
Input_Skeleton = arcpy.GetParameterAsText(0)
if Input_Skeleton == '#' or not Input_Skeleton:
    Input_Skeleton = "Output Skeleton" # provide a default value if unspecified

Output_Line = arcpy.GetParameterAsText(1)
if Output_Line == '#' or not Output_Line:
    Output_Line = "%scratchWorkspace%\\centerline" # provide a default value if unspecified

# Local variables:
dissolve__2_ = Input_Skeleton
centerline = dissolve__2_

# Process: Dissolve
arcpy.Dissolve_management(Input_Skeleton, dissolve__2_, "", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(dissolve__2_, centerline)

# Process: Trim Line
arcpy.TrimLine_edit(centerline, "", "DELETE_SHORT")

