# ---------------------------------------------------------------------------
# Hauteur.py
# Created on: 2013-07-17 23:21:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "H:\\5_STAGE\\indicateurs\\BCaract_Cont\\Proche_Foret\\DataProche.gdb"
arcpy.env.workspace = "H:\\5_STAGE\\indicateurs\\BCaract_Cont\\Proche_Foret\\DataProche.gdb"


# Local variables:
Polyhaid = "H:\\5_STAGE\\ACaract_Obj\\AMorpho2D\\Data_source\\Source_data.gdb\\polyhaid"
MNH = "MNH_LiDAR_50cm_corr_L93"
Field_Map_of_Join_Features = "OBJECTID \"OBJECTID\" true true false 4 Long 0 0 ,First,#,E:\\5_STAGE\\indicateurs\\ACaract_Obj\\CNature_fonc\\AData_source\\Fonction.gdb\\Bois_Test,OBJECTID,-1,-1;Id \"Id\" true true false 4 Long 0 0 ,First,#,E:\\5_STAGE\\indicateurs\\ACaract_Obj\\CNature_fonc\\AData_source\\Fonction.gdb\\Bois_Test,Id,-1,-1;HMean \"HMean\" true true false 0 Float 0 0 ,Mean,#,H:\\5_STAGE\\ACaract_Obj\\AMorpho2D\\Data_source\\sortie.gdb\\RasterT_Extract1,GRID_CODE,-1,-1;HEcartType \"HEcartType\" true true false 50 Double 0 0 ,StdDev,#,E:\\5_STAGE\\indicateurs\\ACaract_Obj\\BPhysio3D\\Data_Source\\Physio3D.gdb\\RasterT_Extract1,GRID_CODE,-1,-1;Hmediane \"Hmediane\" true true false 50 Float 0 0 ,Median,#,E:\\5_STAGE\\indicateurs\\ACaract_Obj\\BPhysio3D\\Data_Source\\Physio3D.gdb\\RasterT_Extract1,GRID_CODE,-1,-1;HMin \"HMin\" true true false 50 Float 0 0 ,Min,#,E:\\5_STAGE\\indicateurs\\ACaract_Obj\\BPhysio3D\\Data_Source\\Physio3D.gdb\\RasterT_Extract1,GRID_CODE,-1,-1;HMax \"HMax\" true true false 50 Float 0 0 ,Max,#,E:\\5_STAGE\\indicateurs\\ACaract_Obj\\BPhysio3D\\Data_Source\\Physio3D.gdb\\RasterT_Extract1,GRID_CODE,-1,-1;HVariance \"Hvariance\" true true false 50 Float 0 0 ,None,#"
Extract_MNH_4 = "H:\\5_STAGE\\ACaract_Obj\\AMorpho2D\\Data_source\\sortie.gdb\\Extract_MNH_1"
RasterT_Extract1 = "H:\\5_STAGE\\ACaract_Obj\\AMorpho2D\\Data_source\\sortie.gdb\\RasterT_Extract1"
Bois_Hauteur = "H:\\5_STAGE\\ACaract_Obj\\AMorpho2D\\Data_source\\sortie.gdb\\polyhaid_SpatialJoin"

# Process: Extraction par masque
arcpy.gp.ExtractByMask_sa(MNH, Polyhaid, Extract_MNH_4)

# Process: Raster vers points
arcpy.RasterToPoint_conversion(Extract_MNH_4, RasterT_Extract1, "Value")


# Process: Jointure spatiale
arcpy.SpatialJoin_analysis(Polyhaid, RasterT_Extract1, Bois_Hauteur, "JOIN_ONE_TO_ONE", "KEEP_ALL", Field_Map_of_Join_Features, "CONTAINS", "", "")

# Process: Calculer un champ
arcpy.CalculateField_management(Bois_Hauteur, "HVariance", "[HEcartType] * [HEcartType]", "VB", "")
