# ---------------------------------------------------------------------------
# PostionTopo.py
# Created on: 2013-07-17 19:43:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os
from arcpy import env

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")



def positionTopo(axehaie, MNT, Bornes, IntersAxePente, workspace):
    """
        axehaie : line model of hedge
        MNT : Digital terrain model
        Bornes : bounds for interpolation of DTM
        IntersAxePente : the output feature class
        workspace : directorie where intermediate feature class will store.
    """
    # paramètre environnement :
    env.overwriteOutput = True
    env.workspace = workspace

    # Process: Pente
    arcpy.gp.Slope_sa(MNT, "PenteRast", "DEGREE", "1")

    # Process: Reclassification (Reclassement = "0 7 1;7 14 2;14 31 3")
    Bornes = Bornes.encode('utf8')
    b1, b2, b3, b4 = Bornes.split(";")
    Reclassement = "%s %s 1;%s %s 2;%s %s 3" %(b1,b2,b2,b3,b3,b4)
    arcpy.gp.Reclassify_sa("PenteRast", "Value", Reclassement, "PenteReclass", "DATA")

    # Process: Raster vers polygones
    arcpy.RasterToPolygon_conversion("PenteReclass", "PolyPente", "NO_SIMPLIFY", "VALUE")

    # Process: Ajouter un champ
    arcpy.AddField_management("PolyPente", "PosTopo", "TEXT", "", "", "20", "", "NULLABLE", "NON_REQUIRED", "")
    expression = """def Transforme (code):
        if code == 1 : valeur = "Faible"
        elif code == 2 : valeur = "Moyen"
        elif code == 3 : valeur = "Fort"
        else : valeur = str(code)
        return valeur """
    # Process: Calculer un champ
    arcpy.CalculateField_management("PolyPente", "PosTopo", "Transforme(!grid_code!)", "PYTHON_9.3", expression)

    # Process: Intersecter
    arcpy.Intersect_analysis([axehaie,"PolyPente"], IntersAxePente, "NO_FID", "", "INPUT")

    # on efface les champs
    arcpy.DeleteField_management(IntersAxePente, ['grid_code','Id'])

if __name__ == "__main__":
    # Paramètres utilisateur :
    axehaie = arcpy.GetParameterAsText(0)
    MNT = arcpy.GetParameterAsText(1)
    Bornes= arcpy.GetParameterAsText(2)
    IntersAxePente = arcpy.GetParameterAsText(3)
    workspace = arcpy.GetParameterAsText(4)
    # lancer la fonction
    positionTopo(axehaie, MNT, Bornes, IntersAxePente, workspace)

